[workspace]
members = [
    "audio_processor",
]
resolver = "2"  # 使用edition 2021的解析器

# 项目工作区配置
# 这是主工作区配置文件，指定了项目包含的成员包

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1 